CREATE TABLE dbo.ReportsArchive
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ReportsArchives PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	MimeType VARCHAR(255) NOT NULL,
	Content VARBINARY(MAX) NOT NULL,
	Parameters NVARCHAR(MAX) NOT NULL,
	PluginName NVARCHAR(255) NOT NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ReportFiles_CreateDate DEFAULT SYSDATETIME()
)
