CREATE TABLE dbo.Reports
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Reports PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	PluginId INT NULL CONSTRAINT FK_Reports_PluginId FOREIGN KEY REFERENCES dbo.ReportPlugins(Id),
	Enabled BIT NOT NULL CONSTRAINT DF_Reports_Enabled DEFAULT 0
);
