CREATE TABLE dbo.ReportPlugins
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ReportPlugins PRIMARY KEY,
	ReportId INT NOT NULL CONSTRAINT FK_ReportPlugins_ReportId FOREIGN KEY REFERENCES dbo.Reports(Id),
	Version VARCHAR(255) NOT NULL,
	Changelog NVARCHAR(MAX) NULL,
	Content VARBINARY(MAX) NOT NULL,
	TemplateContent VARBINARY(MAX) NULL,
	TemplateMimeType VARCHAR(255) NULL,
	TemplateFileName NVARCHAR(255) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ReportPlugins_CreateDate DEFAULT SYSDATETIME()
);
