CREATE TABLE dbo.Users
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Role VARCHAR(255) NOT NULL CONSTRAINT DF_Users_Role DEFAULT 'Guest',
	PasswordHash BINARY(64) NOT NULL,
	CreateDate DATETIME NOT NULL CONSTRAINT DF_Users_CreateDate DEFAULT SYSDATETIME()
)
