CREATE TABLE dbo.Reports
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Reports PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	Enabled BIT NOT NULL CONSTRAINT DF_Reports_Enabled DEFAULT 0
);
