CREATE TABLE dbo.ReportUsers
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ReportUsers PRIMARY KEY,
	ReportId INT NOT NULL CONSTRAINT FK_ReportUsers_ReportId FOREIGN KEY REFERENCES dbo.Reports(Id),
	UserId INT NOT NULL CONSTRAINT FK_ReportUsers_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	AdminId INT NOT NULL CONSTRAINT FK_ReportUsers_AdminId FOREIGN KEY REFERENCES dbo.Users(Id),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ReportUsers_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_ReportUsers UNIQUE (ReportId, UserId)
)
