CREATE TABLE dbo.ReportsArchive
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ReportsArchives PRIMARY KEY,
	PluginId INT NOT NULL CONSTRAINT FK_ReportsArchive_PluginId FOREIGN KEY REFERENCES dbo.ReportBranchPlugins(Id),
	Name NVARCHAR(255) NOT NULL,
	MimeType VARCHAR(255) NOT NULL,
	Content VARBINARY(MAX) NOT NULL,
	Parameters NVARCHAR(MAX) NOT NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ReportsArchives_CreateDate DEFAULT SYSDATETIME()
)
