name: Shearlegs.API

on:
  push:
    branches: [ development ]
    tags:
    - 'v*'

env:
    PROJECT_PATH: 'framework/Shearlegs.API/Shearlegs.API.csproj'
    PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
    NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    name: "Shearlegs.API Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build Project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Get version
      id: version
      uses: batilla7/get-version-action@v2

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ steps.version.outputs.version-without-v }}

    - name: Push to NuGet
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -s
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source ${{ env.NUGET_SOURCE_URL }}
